# Generated by Django 4.2 on 2023-09-26 17:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('username', models.CharField(error_messages={'invalid': 'نام کاربری باید از حروف,اعداد و ـ باشد', 'unique': 'کاربری با این نام وجود دارد'}, max_length=55, null=True, unique=True, validators=[django.core.validators.RegexValidator('([a-zA-Z0-9_]+)', code='invalid', message='نام کاربری نباید از حروف !٬#$%^&*()باشد')], verbose_name='نام کاربری')),
                ('email', models.EmailField(error_messages={'invalid': 'لطفا یک ایمیل معتبر وارد کنید', 'unique': 'کاربری با این ایمیل وجود دارد'}, max_length=128, null=True, unique=True, validators=[django.core.validators.RegexValidator('^([a-zA-Z0-9._%-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,})$', code='invalid', message='ایمیل وارد شده معتبر نمی باشد')], verbose_name='ایمیل')),
                ('phone_number', models.CharField(blank=True, error_messages={'invalid': 'شماره وارد شده نا معتبر است', 'unique': 'این شماره قبلا انتخاب شده است'}, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('(^09)([0-9]{9})', code='invalid', message='شماره وارد شده معتبر نمی باشد')], verbose_name='شماره موبایل')),
                ('credits', models.BigIntegerField(blank=True, null=True, verbose_name='موجودی')),
                ('password', models.CharField(error_messages={'invalid': 'رمز کاربری باید ۸ کاراکتر یا بیشتر باشد و یک حرف بزرگ داشته باشد'}, max_length=255, verbose_name='رمز عبور')),
                ('city', models.CharField(blank=True, db_index=True, max_length=55, null=True, verbose_name='شهر')),
                ('address', models.TextField(blank=True, max_length=555, null=True, verbose_name='ادرس')),
                ('is_superuser', models.BooleanField(db_index=True, default=False, verbose_name='ادمین')),
                ('is_staff', models.BooleanField(db_index=True, default=False, verbose_name='کارکنان')),
                ('ipaddress', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='ایپی ادرس')),
                ('last_password_reset', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ['created_at'],
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='%(class)s', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(blank=True, default='users/profile/default.jpg', null=True, upload_to='media/users/profile/', verbose_name='اواتار')),
                ('first_name', models.CharField(blank=True, max_length=55, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=55, null=True, verbose_name='نام خانوادگی')),
                ('age', models.SmallIntegerField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('job', models.CharField(blank=True, max_length=55, null=True, verbose_name='شغل')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'db_table': 'profiles',
            },
        ),
    ]
