# Generated by Django 4.2 on 2023-09-20 16:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('username', models.CharField(error_messages={'invalid': 'نام کاربری باید از حروف,اعداد و ـ باشد', 'unique': 'کاربری با این نام وجود دارد'}, max_length=55, unique=True, validators=[django.core.validators.RegexValidator('([a-zA-Z0-9_]+)', code='invalid', message='نام کاربری نباید از حروف !٬#$%^&*()باشد')])),
                ('email', models.EmailField(error_messages={'invalid': 'لطفا یک ایمیل معتبر وارد کنید', 'unique': 'کاربری با این ایمیل وجود دارد'}, max_length=128, unique=True, validators=[django.core.validators.RegexValidator('^([a-zA-Z0-9._%-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,})$', code='invalid', message='ایمیل وارد شده معتبر نمی باشد')])),
                ('phone_number', models.CharField(blank=True, error_messages={'invalid': 'شماره وارد شده نا معتبر است', 'unique': 'این شماره قبلا انتخاب شده است'}, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('(^09)([0-9]{9)', code='invalid', message='شماره وارد شده معتبر نمی باشد')])),
                ('credits', models.BigIntegerField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('address', models.TextField(blank=True, max_length=555, null=True)),
                ('is_superuser', models.BooleanField(db_index=True, default=False)),
                ('is_staff', models.BooleanField(db_index=True, default=False)),
                ('ipaddress', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('last_password_reset', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ['created_at'],
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/users/profile/')),
                ('first_name', models.CharField(blank=True, max_length=55, null=True)),
                ('last_name', models.CharField(blank=True, max_length=55, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('job', models.CharField(blank=True, max_length=55, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'db_table': 'profiles',
            },
        ),
    ]
