# Generated by Django 4.2 on 2023-09-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_key_profile_user_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='users/profile/default.jpg', null=True, upload_to='media/users/profile/', verbose_name='اواتار'),
        ),
    ]
