# Generated by Django 4.2 on 2023-09-20 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/users/profile/', verbose_name='اواتار'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='شغل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, max_length=555, null=True, verbose_name='ادرس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=55, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='credits',
            field=models.BigIntegerField(blank=True, max_length=30, null=True, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'لطفا یک ایمیل معتبر وارد کنید', 'unique': 'کاربری با این ایمیل وجود دارد'}, max_length=128, null=True, unique=True, validators=[django.core.validators.RegexValidator('^([a-zA-Z0-9._%-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,})$', code='invalid', message='ایمیل وارد شده معتبر نمی باشد')], verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ipaddress',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='ایپی ادرس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(db_index=True, default=False, verbose_name='کارکنان'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(db_index=True, default=False, verbose_name='ادمین'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(error_messages={'invalid': 'رمز کاربری باید ۸ کاراکتر یا بیشتر باشد و یک حرف بزرگ داشته باشد'}, max_length=255, validators=[django.core.validators.RegexValidator('^([\x08\\w\\d]*)([A-Z]+)([\x08\\w\\d]*)', code='invalid', message='رمز عبور حداقل باید ۸ کاراکتر یا بیشتر باشد و حداقل یک حرف بزرگ داشته باشد')], verbose_name='رمز عبور'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'invalid': 'شماره وارد شده نا معتبر است', 'unique': 'این شماره قبلا انتخاب شده است'}, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('(^09)([0-9]{9})', code='invalid', message='شماره وارد شده معتبر نمی باشد')], verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'invalid': 'نام کاربری باید از حروف,اعداد و ـ باشد', 'unique': 'کاربری با این نام وجود دارد'}, max_length=55, null=True, unique=True, validators=[django.core.validators.RegexValidator('([a-zA-Z0-9_]+)', code='invalid', message='نام کاربری نباید از حروف !٬#$%^&*()باشد')], verbose_name='نام کاربری'),
        ),
    ]
