# Generated by Django 4.2 on 2023-10-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userbasket_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasket',
            name='count',
            field=models.SmallIntegerField(blank=True, default=1, verbose_name='تعداد'),
            preserve_default=False,
        ),
    ]
