# Generated by Django 4.2 on 2023-10-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userbasket_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbasket',
            name='count',
            field=models.SmallIntegerField(blank=True, default=1, verbose_name='تعداد'),
        ),
    ]
