# Generated by Django 4.2 on 2023-10-02 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_discount'),
        ('users', '0005_alter_userbasket_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbasket',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='products.product', verbose_name='کالا'),
        ),
    ]
