# Generated by Django 4.2 on 2023-10-03 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userbasket_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbasket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='users.profile'),
        ),
    ]
