# Generated by Django 4.2 on 2023-10-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userbasket_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbasket',
            old_name='user',
            new_name='profile',
        ),
    ]
