# Generated by Django 4.2 on 2023-10-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_user_userbasket_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='users/profile/default.jpg', null=True, upload_to='users/profile/', verbose_name='اواتار'),
        ),
    ]
