# Generated by Django 4.2 on 2023-10-09 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='sdad', max_length=55, verbose_name='شهر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='sds', error_messages={'invalid': 'نام کاربری باید از حروف,اعداد و ـ باشد', 'unique': 'کاربری با این نام وجود دارد'}, max_length=55, unique=True, validators=[django.core.validators.RegexValidator('([a-zA-Z0-9_]+)', code='invalid', message='نام کاربری نباید از حروف !٬#$%^&*()باشد')], verbose_name='نام کاربری'),
            preserve_default=False,
        ),
    ]
