# Generated by Django 4.2 on 2023-10-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_city_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=55, null=True, verbose_name='شهر'),
        ),
    ]
