# Generated by Django 4.2 on 2023-10-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default='sds', max_length=555, verbose_name='ادرس'),
            preserve_default=False,
        ),
    ]
