# Generated by Django 4.2 on 2023-11-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_created_at_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credits',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='موجودی'),
        ),
    ]
