services:
  db:
    image: "mysql:8.2"
    expose:
      - 3306
    ports:
      - "4000:3306"
    container_name: "db"
    restart: always
    volumes:
      - "/home/mahdiyar/Desktop/digi-market/data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: Mysql@0996
      MYSQL_PASSWORD: Mysql@0996
      MYSQL_DATABASE: digi_market
  redis:
    image: "redis:7.0.8-alpine"
    restart: always
    container_name: "redis"
    command: redis-server --requirepass b446c4229de28d4055ef3261266fa34a8b51bc571436673dea5a70f38c42eb09
    volumes:
      - "/var/lib/redis/:/var/lib/redis/"
      - "./redis:/etc/redis/"
    expose:
      - 6379
  redis-slave:
    image: redis:7.0.8-alpine
    container_name: slave
    ports:
      - "6380:6379"
    command: redis-server --slaveof redis 6379 --requirepass b446c4229de28d4055ef3261266fa34a8b51bc571436673dea5a70f38c42eb09
    depends_on:
      - redis
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: "webserver:test"
    restart: always
    container_name: "backend"
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: Mysql@0996
      REDIS_HOST: redis
      REDIS_SLAVE_HOST: slave
      REDIS_PORT: 6379
      REDIS_DB: 1
    volumes:
      - ".:/app"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  nginx:
    image: "nginx:1.25.3"
    restart: always
    container_name: "nginx"
    volumes:
      - "./nginx/:/etc/nginx/"
      - "/etc/ssl/:/etc/ssl/"
      - "./static:/var/www/static"
      - "./media:/var/www/media"
    ports:
      - "80:80"
    depends_on:
      - backend
networks:
  default:
    name: "server-net"
    internal: true