# Generated by Django 4.2 on 2023-09-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='name',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
