# Generated by Django 4.2 on 2023-09-27 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='avatar',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='products/category/avatar/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='avatar',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='products/subcategory/avatar/'),
            preserve_default=False,
        ),
    ]
