# Generated by Django 4.2 on 2023-09-27 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_foreign_subcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'sub_categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'sub_category', 'verbose_name_plural': 'sub_categories'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='sub_categories',
        ),
    ]
