# Generated by Django 4.2 on 2023-09-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_category_alter_productcomment_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomment',
            options={'ordering': ['rating', 'updated_at', 'created_at'], 'verbose_name': 'product-comment', 'verbose_name_plural': 'products_comments'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'product_image', 'verbose_name_plural': 'products_images'},
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='comment',
            field=models.TextField(default=5, verbose_name='دیدگاه'),
        ),
        migrations.AlterModelTable(
            name='productcomment',
            table='products_comments',
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='product_images',
        ),
    ]
