# Generated by Django 4.2 on 2023-09-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productimage',
            table='products_images',
        ),
    ]
