# Generated by Django 4.2 on 2023-09-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productimage_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], db_index=True, default=1, verbose_name='امتیاز'),
            preserve_default=False,
        ),
    ]
