# Generated by Django 4.2 on 2023-10-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productcomment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='comment',
            field=models.TextField(verbose_name='دیدگاه'),
        ),
    ]
