# Generated by Django 4.2 on 2023-10-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productcomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, max_length=55, verbose_name='تخفیف'),
        ),
    ]
