# Generated by Django 4.2 on 2023-10-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avatar',
            field=models.ImageField(blank=True, default=1, upload_to='products/avatar/', verbose_name='آواتار'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(default=1, verbose_name='قیمت'),
            preserve_default=False,
        ),
    ]
