# Generated by Django 4.2 on 2023-10-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
    ]
