# Generated by Django 4.2 on 2023-10-10 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_description_producttags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttags',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='products.product', verbose_name='محصول'),
        ),
    ]
