# Generated by Django 4.2 on 2023-10-12 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_producttags_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='نام'),
        ),
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین اپدیت')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='نام')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='products.subcategory', verbose_name='مجموعه')),
            ],
            options={
                'verbose_name': 'sub_sub_category',
                'verbose_name_plural': 'sub_sub_categories',
                'db_table': 'sub-sub-categories',
            },
        ),
    ]
