# Generated by Django 4.2 on 2023-10-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_subsubcategory_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsubcategory',
            name='details',
            field=models.JSONField(blank=True, null=True, verbose_name='جزییات'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='brand',
            field=models.JSONField(blank=True, null=True, verbose_name='برند'),
        ),
    ]
