# Generated by Django 4.2 on 2023-10-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_subsubcategory_details_alter_subsubcategory_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsubcategory',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='products/subsubcategory'),
        ),
    ]
